methodName: replaceCategories
OutboundObject: SetCategoriesRequest
outboundObject: SetCategoriesRequest
javaUrlPath: + setCategoriesRequest.getMenuId() + "/subcategories"
HTTP_METHOD: PUT
destinationClass: MenuClient
